### ISSUE TITLE
0.18.0 Regular Expression Denial of Service

### ISSUE THREAD

**Issue by naxxateux** [aMarCruz/eslint-plugin-prettierx#10]
Hi.

My yarn audit check started showing me Regular Expression Denial of Service issues during tests.

<img width="607" alt="Screen Shot 2021-05-25 at 11 55 06" src="https://user-images.githubusercontent.com/5010981/119469709-4950d680-bd50-11eb-8683-be0bfe67bab9.png">
<img width="607" alt="Screen Shot 2021-05-25 at 11 55 19" src="https://user-images.githubusercontent.com/5010981/119469726-4c4bc700-bd50-11eb-9e5f-4154ec6e3299.png">

How can I properly resolve them? Do I need to wait package update here or can I do it myself somehow?

**Comment by aMarCruz** [comment]
@naxxateux , sorry by the delay.
The versions of the dependencies are updated at different times.
You can wait or use a tool like [patch-package](https://www.npmjs.com/package/patch-package) to change versions
