### ISSUE TITLE
`printWidth` is not respected

### ISSUE THREAD

**Issue by nolde** [aMarCruz/eslint-plugin-prettierx#3]
I have modified default `printWidth` to 100. It is not being respected by `eslint-plugin-prettierx`.

## .eslintrc.js
```js
module.exports = {
  root: true,
  parserOptions: {
    ecmaVersion: 9,
    sourceType: 'module'
  },
  env: {
    node: true,
    es6: true
  },
  plugins: [
    'node',
    'prettierx'
  ],
  extends: [
    'plugin:node/recommended',
    'plugin:prettierx/standardx'
  ],
  settings: {
    prettierx: {
      usePrettierrc: true,
      editorconfig: true,
      useCache: false
    }
  },
  rules: {
    'node/no-extraneous-require': 0
  }
}
```

## .prettierrc
```
{
  "printWidth": 100,
  "semi": false,
  "singleQuote": true,
  "jsxBracketSameLine": true,
  "endOfLine": "lf",
  "spaceBeforeFunctionParen": true
}
```

## .editorconfig
```
root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[*.{json,js,yml}]
indent_style = space
indent_size = 2
max_line_length = 100

[*.{md}]
indent_style = space
indent_size = 4
```

Running command `eslint . --ext .js --config .eslintrc.js`, I get complaints about line size that are above the default prettier length, but below 100.

**Comment by aMarCruz** [comment]
@nolde thanks for your report. I will check it asap

**Comment by aMarCruz** [comment]
for now, please try adding this rule:

```js
  rules: {
    'prettierx/options': ['error', { printWidth: 100 }],
```

**Comment by nolde** [comment]
I will try that and let you know.
Ah, forgot some useful info:
```js
"devDependencies": {
  // ..
  "eslint": "6.1.0",
  "eslint-plugin-node": "9.1.0",
  "eslint-plugin-prettierx": "0.4.0",
  // ..
}
```

**Comment by nolde** [comment]
Hi!

Adding the [rule mentioned above](#issuecomment-515114278) made the specific width error go away, but several other `prettierx/options` errors appeared throughout the project, which weren't there before.

Looks like adding that line changes more than it should. I have also tried appending a `.json` to `.prettierrc` and use the following line...
```
'prettierx/options': ['error', require('./.prettierrc.json')]
```
... but I got the same results as when using just `printWidth` in it.

**Comment by nolde** [comment]
Adding the [rule you mentioned](#issuecomment-515114278) works! Thank you!

**Comment by aMarCruz** [comment]
Please test with v0.11.0
I hope this issue has been resolved.

**Comment by nolde** [comment]
Confirmed -- issue has been fixed. Thank you!
