### ISSUE TITLE
breakBeforeElse

### ISSUE THREAD

**Issue by lambert-velir** [aMarCruz/eslint-plugin-prettierx#4]
Hi!
I'm pretty frustrated with https://github.com/prettier/prettier/issues/840, so I'm looking to use the [`breakBeforeElse`](https://github.com/brodybits/prettierx#additional-prettierx-options) option in prettierx instead of prettier, however, it doesn't appear that `eslint-plugin-prettierx` supports this option currently.  

Here's how I have it set up in my `eslintrc.json` rules section:
```
"prettierx/options": [
  1,
  {
    "breakBeforeElse": true
  }
],
```

When I try to run eslint in Atom, I get an error:
```
.eslintrc.json: Configuration for rule "prettierx/options" is invalid: Value {"breakBeforeElse":true} should NOT have additional properties.
```

Am I missing something? or does this need to be added to the `eslint-plugin-prettierx` [schema](https://github.com/aMarCruz/eslint-plugin-prettierx/blob/c5176656b466f64b96d6e1160173f564ee1462e1/lib/schemas/prettierx.json) in order to work?

Thanks!

**Comment by lambert-velir** [comment]
@aMarCruz is this something we can add?

**Comment by aMarCruz** [comment]
@lambert-velir hi, I'll work on this ASAP

**Comment by aMarCruz** [comment]
@lambert-velir ,
eslint-plugin-prettierx v0.12.0 w/`breakBeforeElse` support is in npm.
Please test it.

**Comment by lambert-velir** [comment]
@aMarCruz I just tested it out and it working, thanks for adding this! 🙌🏻
