### ISSUE TITLE
“Clearing config cache” warning

### ISSUE THREAD

**Issue by ai** [aMarCruz/eslint-plugin-prettierx#6]
Every time I start ESLint I see the same warning:

```sh
$ npx eslint .
Clearing config cache ...
```

What does it mean? Does it mean that there is a problem with my config?

Should we remove it or make the text more clear?

**Comment by aMarCruz** [comment]
@ai , there's no problem. It is prettier clearing its cache. I will make the text clearer.
Sorry for the delay and thanks for your feedback.

**Comment by aMarCruz** [comment]
@ai , I removed the warning.
